### PR TITLE
Added display of quoteValue.

### PR DESCRIPTION
**Pull request by ctubio**
After this PR it looks like (for example):
fiat

Please feel free to request any modification to make this PR match your expectations.

### CODE REVIEW

**Comment by michaelgrosner** [comment]
This looks great. I prefer instead of "fiat" you'd use "quote" as I use "quote" elsewhere throughout the codebase. Thank you!

**Comment by ctubio** [comment]
Thanks for your feedback,
you mean to rename the `public valueFiat` property with the new name of **valueQuote**?

(note that just below line  https://github.com/ctubio/tribeca/blob/add_fiatvalue_display/src/common/models.ts#L272 there is already a property named `quoteValue`, this will not cause confusion to have `valueQuote` and `quoteValue` together in the same object?)

Please confirm this and i will proceed.

**Comment by michaelgrosner** [comment]
I actually think `quoteValue` does already the calculation we need.

**Comment by ctubio** [comment]
lol so [silly](https://github.com/ctubio/tribeca/blob/83a355e94faf4b5b345942034033f9a8fbcf04d7/src/service/broker.ts#L378).

Thanks to your feedback now is OK.
let me know if you want me to rebase and squash the branch to 1 commit.

**Pull request merged**
