### PR TITLE
Fixed height of messageOptions.

### LINKED ISSUE #25: Box too short on UI
Cant read the 't'/'text' box content bellow 'market data and quote' in my screen

### PR DESCRIPTION
**Pull request by ctubio**
Hello,
this small css modification hopes to fix #25 
but im not sure cos looks like really the code is trying to hide the grid header (if the header is correctly  hidden then may be OK to have there those original 50px, but for me the header is visible so i added some px).

### CODE REVIEW

**Comment by michaelgrosner** [comment]
What browser are you using? On Chrome on my Mac, this looks too long. I don't know much of CSS or cross-browser design - I don't know if there's something I can do to fix it everywhere.

One fix we can do in the short-term is in `messageOptions` in the controller, change `hideHeader: true` to `showHeader: false` (http://stackoverflow.com/a/27633795/178073)

**Comment by ctubio** [comment]
Many thanks for the link,
i will test it under multiple platforms and let you know if i did any good (while tryin to effectively hide the headers of the relevant tables but keeping the same layout)

Expect new commits from myself in this PR soon (if nobody fixes this before).

**Comment by ctubio** [comment]
After the previous commits in all the OS and browsers that i have tested it looks like:
box

Seems like the previous modification at c0c37bc is still needed so i didn't revert it.

**Comment by michaelgrosner** [comment]
My browser is still showing:

image

**Comment by ctubio** [comment]
sorry for the trouble, hope you see it correctly now.

**Pull request merged**
